---
- name: install WinZip
  hosts: all

  tasks:
  - name: create directory
    win_file:
      path: C:\ansible
      state: directory
  - name: download 7zip from URL
    win_get_url:
      url: https://download.winzip.com/wzipse40.msi
      dest: C:\ansible
  - name: install 7 zip
    win_package:
      path: 'C:\ansible\wzipse40.msi'
      state: present
  - name: uninstall 7 zip
    win_package:
      path: 'C:\ansible\wzipse40.msi'
      state: absent
  - name: remove 7zip install folder
    win_file:
      path: C:\ansible
      state: absent
