---
- name: install WinZip
  hosts: all

  tasks:
  - name: create directory
    win_file:
      path: C:\ansible
      state: directory
  - name: download Winzip from URL
    win_get_url:
      url: https://download.winzip.com/wzipse40.msi
      dest: C:\ansible
  - name: install Winzip
    win_package:
      path: 'C:\ansible\wzipse40.msi'
      state: present
